"""create_all_tables

Revision ID: 0ab1dccf4126
Revises: 
Create Date: 2026-03-06 23:57:08.964653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab1dccf4126'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('sub_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sub_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_table('availability_slots',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('day_of_week', sa.Enum('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='day_of_week'), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('session_request', 'session_accepted', 'session_rejected', 'session_completed', 'payment_received', 'withdrawal_processed', 'general', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_profile',
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('per_30_mins_charges', sa.Integer(), nullable=True),
    sa.Column('upi_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_table('teacher_subject_master_list',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('sub_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sub_id'], ['subject.sub_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_video_demo',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('sub_id', sa.String(length=255), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sub_id'], ['subject.sub_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_wallet',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('teacher_id', sa.String(length=255), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_withdraw', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('user_profile',
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_name'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_table('withdrawal',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('teacher_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'success', 'failed', name='withdrawal_status'), nullable=False),
    sa.Column('request_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_schedule',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('teacher_id', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=255), nullable=False),
    sa.Column('subject_master_id', sa.String(length=255), nullable=False),
    sa.Column('topic_description', sa.Text(), nullable=True),
    sa.Column('slot_id', sa.String(length=255), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'accepted', 'rejected', 'rescheduled', 'completed', 'cancelled', name='session_status'), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['availability_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_master_id'], ['teacher_subject_master_list.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('rated_by', sa.String(length=255), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rated_by'], ['user.user_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('session_schedule')
    op.drop_table('withdrawal')
    op.drop_table('user_profile')
    op.drop_table('teacher_wallet')
    op.drop_table('teacher_video_demo')
    op.drop_table('teacher_subject_master_list')
    op.drop_table('teacher_profile')
    op.drop_table('notification')
    op.drop_table('availability_slots')
    op.drop_table('user')
    op.drop_table('subject')
    # ### end Alembic commands ###
