"""add_room_name_to_session

Revision ID: eedd1b26b1f8
Revises: 0ab1dccf4126
Create Date: 2026-03-08 17:49:43.330900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eedd1b26b1f8'
down_revision: Union[str, Sequence[str], None] = '0ab1dccf4126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_schedule', sa.Column('room_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_schedule', 'room_name')
    # ### end Alembic commands ###
