"""add_group_session_support

Revision ID: f5baeaa2ba39
Revises: eedd1b26b1f8
Create Date: 2026-03-17 18:12:42.558678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5baeaa2ba39'
down_revision: Union[str, Sequence[str], None] = 'eedd1b26b1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create new ENUM types first (required by PostgreSQL before column ADD)
    session_type_enum = sa.Enum('individual', 'group', name='session_type')
    session_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_enrollment',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('enrolled', 'cancelled', name='enrollment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session_schedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_enrollment_session_student')
    )
    op.add_column('session_schedule', sa.Column('session_type', sa.Enum('individual', 'group', name='session_type'), nullable=False, server_default='individual'))
    op.add_column('session_schedule', sa.Column('max_students', sa.Integer(), nullable=True))
    op.alter_column('session_schedule', 'student_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('teacher_profile', sa.Column('group_per_student_charges', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profile', 'group_per_student_charges')
    op.alter_column('session_schedule', 'student_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('session_schedule', 'max_students')
    op.drop_column('session_schedule', 'session_type')
    op.drop_table('session_enrollment')
    # Drop ENUM types created during upgrade
    sa.Enum(name='session_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='enrollment_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
